### ISSUE TITLE
Segfault when multiple prefixes defined with only one interface

### ISSUE THREAD

**Issue by JKJameson** [npd6/npd6#68] opened 2016-06-05 11:57 UTC
Consider the following config (where all prefixes are expected to be routed at interface br0)
prefix=2a04:xxxx:1:5:
prefix=2a04:xxxx:1:8:
interface = br0

The code above results in a segfault. The correct configuration is;
prefix=2a04:xxxx:1:5:
interface = br0
prefix=2a04:xxxx:1:8:
interface = br0

In other words, one interface line per prefix.

Some kind of error would be useful, I had to debug with valgrind to trace this issue.

**Comment by npd6** [comment] 2016-06-08 08:13
Yup, that could do with improving. Agreed.

**Comment by npd6** [comment] 2017-11-07 13:29
Just finishing the multiple dynamic interface coding, and will then test/fix this. (Since those changes may yet have an impact on this issue)

**Comment by npd6** [comment] 2019-05-03 08:39
Closing as old and I neglected it. However also cannot reproduce as-is - the config case given will be caught in the config parsing code. "readConfig: Must have same number of prefixes as interfaces. Interfaces = 1, Prefixes = 2"

So there must also have been some other condition that made this dump. So cannot reproduce here (yet).

**Closed as completed** 2019-05-03 08:39 UTC
Labels: bug
